"""Recreated employee table

Revision ID: 848875ad1c19
Revises: 
Create Date: 2025-03-19 10:06:34.347975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848875ad1c19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Adef downgrade() -> None:
    
    
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('speed_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('accuracy_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trajectory_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('work_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('compliance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employees_pkey'),
    sa.UniqueConstraint('employee_id', name='employees_employee_id_key')
    )
    op.create_table('customer_config',
    sa.Column('customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('conf_threshold', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.2'), autoincrement=False, nullable=True),
    sa.Column('iou_threshold', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.45'), autoincrement=False, nullable=True),
    sa.Column('max_age', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True),
    sa.Column('n_init', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customer_id', name='customer_config_pkey')
    )
    # ### end Alembic commands ###
# ### alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    pass
